const houseData = [
    {
        id: 1,
        name: "Porto Letizia room como 8",
        image: "../images/porto-letizia.jpeg",
        sleeps: 6,
        bedrooms: 2,
        bathroom: 1,
        surface: "40m²",
        needsCleaning: true,
        location: "Porlezza, Italy",
        room: "Como 8",
        status: "",
        guests: "Familia Corleone",
        picture: "",
        date: "2023-12-24T10:00:00.000Z",
        houseInfo: []
    },
    {
        id: 2,
        name: "Porto Letizia Tulipano 5 ID 593",
        image: "../images/porto-letizia.jpeg",
        sleeps: 6,
        bedrooms: 2,
        bathroom: 1,
        surface: "40m²",
        needsCleaning: true,
        location: "Porto Letizia",
        room: "Milano 2",
        status: "",
        guests: "Andrea Lubberdink",
        picture: "",
        date: "2023-12-24T10:00:00.000Z",
        houseInfo: []
    },
    {
        id: 3,
        name: "Porto Letizia Tulipano 5 ID 593",
        image: "../images/porto-letizia.jpeg",
        needsCleaning: false,
        location: "Porto Letizia",
        room: "Milano 4",
        status: "",
        guests: "gekke mevrouw",
        picture: "",
        date: "2023-12-21T00:10:00.00Z",
        houseInfo: []
    },
    {
        id: 4,
        needsCleaning: false,
        location: "Porto Letizia",
        name: "doet er niet toe",
        sleeps: 6,
        bedrooms: 2,
        bathroom: 1,
        surface: "40m²",
        room: "Milano 4",
        status: "",
        guests: "gekke mevrouw 2",
        picture: "",
        date: "2023-12-22T00:10:00.000Z",
        instructions: "Full cleaning ask instructions at Mab: +3964887633",
        houseInfo: []
    },
    {
        id: 5,
        name: "Porto Letizia como 2",
        image: "../images/porto-letizia.jpeg",
        sleeps: 2,
        bedrooms: 1,
        bathroom: 1,
        surface: "40m²",
        needsCleaning: true,
        location: "Porlezza, Italy",
        room: "Como 2",
        status: "",
        guests: "Familia Corleone",
        picture: "",
        date: "2023-10-26T10:00:00.000Z",
        instructions: "Full cleaning ask instructions at Mab: +3964887633",
        houseInfo: []
    },
    {
        id: 6,
        name: "Porto Letizia como 2",
        image: "../images/porto-letizia.jpeg",
        sleeps: 2,
        bedrooms: 1,
        bathroom: 1,
        surface: "40m²",
        needsCleaning: false,
        location: "Porlezza, Italy",
        room: "Como 2",
        status: "",
        guests: "Familia Corleone",
        picture: "",
        date: "2023-07-11T10:00:00.000Z",
        instructions: "Full cleaning ask instructions at Mab: +3964887633",
        houseInfo: []
    },
    {
        id: 7,
        name: "Garda Experience",
        image: "../images/porto-letizia.jpeg",
        sleeps: 2,
        bedrooms: 1,
        bathroom: 1,
        surface: "40m²",
        needsCleaning: true,
        location: "Porlezza, Italy",
        room: "Como 2",
        status: "",
        guests: "Familia Corleone",
        picture: "",
        date: "2023-02-09T10:00:00.000Z",
        instructions: "Full cleaning ask instructions at Mab: +3964887633",
        houseInfo: []
    },
    {
        id: 8,
        name: "Mijn kamer",
        image: "../images/porto-letizia.jpeg",
        sleeps: 6,
        bedrooms: 2,
        bathroom: 1,
        surface: "40m²",
        needsCleaning: true,
        location: "Porto Letizia",
        room: "Milano 2",
        status: "",
        guests: "Andrea Lubberdink",
        picture: "",
        date: "2023-12-19T10:00:00.000Z",
        instructions: "Full cleaning ask instructions at Mab: +3964887633",
        houseInfo: []
    },
]

export default houseData;